name: 'Docker check'

on:
  pull_request:
    paths:
      - 'Dockerfile'
      - '.github/workflows/docker-pr.yml'
      - '.github/workflows/prod-deploy.yml'

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Build Docker image
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6.19.2
        with:
          context: .
          push: false
